main = "./src/index.ts"
name = "unfurl-worker"
compatibility_date = "2023-01-18"
node_compat=true
account_id="9840f8a36a817b103e00e29a0e2bad6f"
minify=true

[dev]
ip = "localhost"
port = 8007
local_protocol = "http"

[vars]
# VAR_NAME = "some_value"
ENVIRONMENT = "development"

# The necessary secrets are:
# TWITTER_BEARER
# AUTH_SECRET
#
# for local development, you can add these in .dev.vars
#
# For production, you can add these in the Cloudflare dashboard or run
# `echo <VALUE> | wrangler secret put <NAME>` for each of these
# for production, the secrets must be deployed behind the production flag
# `echo <VALUE> | wrangler secret put <NAME> --env production`
# OR
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

# production routes
# yarn publish:prod
[env.production]
routes = [{ pattern = "unfurl-worker.towns.com", custom_domain = true }]
vars = { ENVIRONMENT = "production" }

# test routes
# yarn publish:test
[env.test]
routes = [{ pattern = "unfurl-worker-test.towns.com", custom_domain = true }]
vars = { ENVIRONMENT = "test" }
