services:
    xchain-monitor:
        build:
            context: ../../
            dockerfile: ./apps/xchain-monitor/Dockerfile
        environment:
            RIVER_ENV: omega
            INITIAL_BLOCK_NUM: 25750000
            TRANSACTION_VALID_BLOCKS: 20
            BASE_PROVIDER_URL: https://mainnet.base.org
